name: Build Windows App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout AutoSubs Repo Code
        uses: actions/checkout@v4

      - name: Install Vulkan SDK
        run: |
          choco install vulkan-sdk -y
          $vulkanPath = (Get-ChildItem -Path "C:\VulkanSDK" -Directory | Sort-Object Name -Descending | Select-Object -First 1).FullName
          echo "VULKAN_SDK=$vulkanPath" >> $env:GITHUB_ENV

      - name: Install LLVM
        run: choco install llvm -y
          
      - name: Install Node deps
        run: |
          npm ci --prefix Adobe-Extension
          npm ci --prefix AutoSubs-App

      - name: Download ffmpeg binary
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd AutoSubs-App/src-tauri
          mkdir binaries
          cd binaries
          gh release download --repo tmoroney/ffmpeg-binaries --pattern "ffmpeg-x86_64-pc-windows-msvc.zip" --clobber
          7z e ffmpeg-x86_64-pc-windows-msvc.zip

      - name: Build Tauri
        continue-on-error: true
        env:
          LIBCLANG_PATH: 'C:\Program Files\LLVM\bin'
          CARGO_TARGET_DIR: 'C:\cargo-target'
        run: |
          cd AutoSubs-App
          npm run tauri build -- -- --no-default-features --features windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoSubs-Windows-EXE
          path: C:\cargo-target\release\bundle\nsis\*.exe
          if-no-files-found: error
